# Generated by Django 5.1.3 on 2024-11-22 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attractions', '0002_auto_20241111_1902'),
    ]

    operations = [
        migrations.AlterField(
            model_name='province',
            name='name',
            field=models.CharField(choices=[('北京', 'Beijing'), ('天津', 'Tianjin'), ('河北', 'Hebei'), ('山西', 'Shanxi'), ('内蒙古', 'Neimenggu'), ('辽宁', 'Liaoning'), ('吉林', 'Jilin'), ('黑龙江', 'Heilongjiang'), ('上海', 'Shanghai'), ('江苏', 'Jiangsu'), ('浙江', 'Zhejiang'), ('安徽', 'Anhui'), ('福建', 'Fujian'), ('江西', 'Jiangxi'), ('山东', 'Shandong'), ('河南', 'Henan'), ('湖北', 'Hubei'), ('湖南', 'Hunan'), ('广东', 'Guangdong'), ('广西', 'Guangxi'), ('海南', 'Hainan'), ('重庆', 'Chongqing'), ('四川', 'Sichuan'), ('贵州', 'Guizhou'), ('云南', 'Yunnan'), ('西藏', 'Xizang'), ('陕西', 'Shaanxi'), ('甘肃', 'Gansu'), ('青海', 'Qinghai'), ('宁夏', 'Ningxia'), ('新疆', 'Xinjiang'), ('台湾', 'Taiwan'), ('香港', 'Hongkong'), ('澳门', 'Macau')], max_length=50, unique=True),
        ),
    ]
